import type { Metadata } from "next";
import "./globals.css";
import Layout from "./layout/Layout";
import { Comfortaa } from "next/font/google";
import { UserContext } from "@/common/components/UserContext";

export const comfortaa = Comfortaa({
  weight: ["600", "400"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "SwiftConnect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={comfortaa.className}>
        <UserContext>
          <Layout>{children}</Layout>
        </UserContext>
      </body>
    </html>
  );
}
